### ISSUE TITLE
rosdep のバージョンがふるいとインストールできないのでバージョンを確認する

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_common#1008]
@yuki-asano jsk.rosinstall でバージョンをチェックするといいですね

```
原因は、
rosdepのバージョンが古かったことで、
sudo aptitude install python-rosdep
した後に、
もう一度インストールしなおしたら治りました。
```

**Comment by wkentaro** [comment]
http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/precise/main/binary-amd64/Packages
In hydro the latest version for apt is 0.11.2?
