### ISSUE TITLE
[question] [jsk_data] What's difference b/w large and small?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#1114]

**Comment by garaemon** [comment]
I forget the original reason but... probably size of the file.

IMO, you can make them into one directory and remove large/small.

**Comment by wkentaro** [comment]
thanks.
I'd like to hear @k-okada 's opinion also.

2015年9月5日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> I forget the original reason but... probably size of the file.
>
> IMO, you can make them into one directory and remove large/small.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1114#issuecomment-137931824>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
just a size.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
should we keep  both large and small?

2015年9月7日月曜日、Kei Okada<notifications@github.com>さんは書きました:

> just a size.
>
> --
> ◉ Kei Okada
>
>
> On Sat, Sep 5, 2015 at 5:53 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > thanks.
> > I'd like to hear @k-okada 's opinion also.
> >
> > 2015年9月5日土曜日、Ryohei Ueda<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
> >
> > > I forget the original reason but... probably size of the file.
> > >
> > > IMO, you can make them into one directory and remove large/small.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/jsk-ros-pkg/jsk_common/issues/1114#issuecomment-137931824
> > >
> > > .
> > >
> >
> >
> > --
> > 和田 健太郎 / Kentaro Wada
> > http://wkentaro.com <http://www.wkentaro.com>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/issues/1114#issuecomment-137932481
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1114#issuecomment-138183092>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
i'm not sure what's happening in this package, but originally we design
`make small` for those who would like to check out useable datas and `make
lerge` for downloading all datas. so if new system can handle that, it ok.

--
◉ Kei Okada

**Comment by k-okada** [comment]
it does not mean that we have to keep same command, just to keep same idea,
we want provide recommended dataset for beginners.

--
◉ Kei Okada

**Comment by garaemon** [comment]
Something like...

* `jsk_data get --smaller-than 100M`
* `jsk_data get --small`
* `jsk_data get --newer-than 2015:08:20`
* `jsk_data ls --size-sort`
* `jsk_data ls --date-sort`
