### ISSUE TITLE
Why jsk-ros-pkg/* version is not set in jsk.rosinstall as master?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#1116]
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk.rosinstall

**Comment by garaemon** [comment]
Our policy does not allow maintain multiple branches

**Comment by wkentaro** [comment]
What do you mean?

I mean it helps the version divergence of repositories in workspace (i mean
sanity).
like:
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tools/bin/ws_doctor.py
wstool supports only divergence b/w local branches at present, but b/w
local and remote feature is coming.
https://github.com/vcstools/wstool/pull/38


2015年9月5日土曜日、Ryohei Ueda<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> Our policy does not allow maintain multiple branches
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1116#issuecomment-137928699>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by garaemon** [comment]
Having version info in rosinstall is redundant because we have only one branch in jsk-ros-pkg 
only thinking about `wstool update`.

But the information can help something, you can add them.

**Comment by wkentaro** [comment]
specifying master is helpful when user unexpectedly on the other branch
than master. it invokes V status flag as warning in wstool info.

2015年9月5日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> Having version info in rosinstall is redundant because we have only one
> branch in jsk-ros-pkg
> only thinking about wstool update.
>
> But the information can help something, you can add them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1116#issuecomment-137930082>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
