### ISSUE TITLE
[enhancement] [jsk_topic_tools] warning when using rosrun and there is no subscriber for seconds

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#1132]
why not add this feature to jsk_topic_tools/ConnectedBasedNodelet?
This feature is similar as warning when we run image_view without remapping `image` topic.

**notice**
* And this is only for `rosrun`.
* warning should be only once.
* warning will appear after around 2~5 seconds.

maybe using timer with callback function and flag to avoid many warnings.

**Comment by garaemon** [comment]
This kind of information is available on `/diagnostics`.
ConnectoinBasedNodelet publishes information about publishers and their subscribers to diagnostics.

**Comment by wkentaro** [comment]
Oh, sorry. I mean this is not for professionals but for beginners. (I think
the warning of image_view is also for beginners.)


2015年9月19日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> This kind of information is available on /diagnostics.
> ConnectoinBasedNodelet publishes information about publishers and their
> subscribers to diagnostics.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1132#issuecomment-141633992>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
I agree that those kinds of warning helps us a lot, OTH I can easily imagine users say
"I have these warning message, this is a problem" and I will answer "It is an expected warning because no program require output yet ".

**Comment by wkentaro** [comment]
This idea came from my experience, and I think this is useful for people
who are willing to resolve problems by theirselves. This can save their
time.

I think I understood your concern, that's true the warning does not work
for people who does not read the warning message well.

2015年9月21日月曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> I agree that those kinds of warning helps us a lot, OTH I can easily
> imagine users say
> "I have these warning message, this is a problem" and I will answer "It is
> an expected warning because no program require output yet ".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1132#issuecomment-141921347>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
OK, let's see how it is useful. Please implement that feature.

**Comment by wkentaro** [comment]
I'm planning to use [roscpp::Timer](http://wiki.ros.org/roscpp/Overview/Timers) with `oneshot` argument.
Do you agree with this way?

**Comment by garaemon** [comment]
WallTimer sounds better
