### ISSUE TITLE
[enhancement] [jsk_data] Select file to install interactively

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_common#1141]
I'd like to install file interactively when I'm using jsk_data.
one useful library is [python-inquirer](https://github.com/magmax/python-inquirer)

**Comment by wkentaro** [comment]
:+1: 

we can also use percol::
![out](https://cloud.githubusercontent.com/assets/4310419/10267363/543dcbd4-6acc-11e5-9c62-d93876b416dd.gif)

**Comment by garaemon** [comment]
Can you invoke percole in `jsk_data get` and select file by percole and download it?
