### ISSUE TITLE
jsk_data put rename file destructively

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_common#1143]
I think it should not rename local file

**Comment by wkentaro** [comment]
How can we upload file with rsync with renaming only the destination? 
Or should we use another tool to upload?

**Comment by garaemon** [comment]
hmm, copy to `/tmp`?

**Comment by wkentaro** [comment]
Or after uploading rename it remotely.

2015年9月29日火曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> hmm, copy to /tmp?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/issues/1143#issuecomment-144018880>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
So implementation without renaming seems possible, but I think current
bahaivor is simple and good enough.

People should add time stamp in file name, especially for log files
and movies. That is good practice.

Also I considered the renaming can be confusing so added user confirmation.

2015年9月29日火曜日、Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> Or after uploading rename it remotely.
>
> 2015年9月29日火曜日、Ryohei Ueda<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> hmm, copy to /tmp?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsk-ros-pkg/jsk_common/issues/1143#issuecomment-144018880>
>> .
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
I understood

**Comment by garaemon** [comment]
BTW, rsync with renaming file may be possible. http://stackoverflow.com/questions/1312411/using-rsync-to-rename-files-during-copying-with-files-from

**Comment by wkentaro** [comment]
I see, so maybe we can change the behavior when the force renaming is realized really dangerous.
or add option --no-local-rename.
