### ISSUE TITLE
[Super Lower Priority] why rtd does not have documents of jsk_tools?

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_common#1250]
how can  I add https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tools/README.md to  https://jsk-common.readthedocs.org/en/latest/ ?

**Comment by wkentaro** [comment]
Need to move README.md here as doc/jsk_tools/index.md.

**Comment by wkentaro** [comment]
It does not take time, so I fixed it. in #1251

**Comment by wkentaro** [comment]
Please close.
