### ISSUE TITLE
Request of next release of 2.0.4

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#1252]
![image](https://cloud.githubusercontent.com/assets/4310419/11469644/2e77901e-979b-11e5-9a0b-552985df1f8a.png)

upper commits are needed to make tests pass on other repository like `jsk_recognition`.
Sorry for taking your time, but could you please do next release?

**Comment by k-okada** [comment]
release is very easy , use
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/add_tag/ and
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/bloom_release/

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Thank you.
