### ISSUE TITLE
Release new version: indigo 2.0.13

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#1381]
@k-okada Could you please do this?

I need some fixes of jsk_tools in https://github.com/jsk-ros-pkg/jsk_model_tools/pull/175 .

**Comment by wkentaro** [comment]
done. https://github.com/ros/rosdistro/pull/11328

**Comment by k-okada** [comment]
if you plan to increase number of packages that depends on jsk_tools,
please define 'stable api/tool set' which may list of api , tools will not
change, newer release version must not change the interface


--
◉ Kei Okada

**Comment by wkentaro** [comment]
What exactly do I need to do?
Should I write an API specification?
