### ISSUE TITLE
jsk-common.readthedocs.io is deprecated?

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_common#1392]
recent changes does not affect `jsk-common.readthedocs.io`, but `jsk-docs.readthedocs.io`.
Is `jsk-common.readthedocs.io` is deprecated? If so, I think it's good idea to disable its site for avoiding confusion.

**Comment by k-okada** [comment]
thanks. disabled

--
◉ Kei Okada
