### ISSUE TITLE
using voice_text with sound_play occurs high load?

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_common#1401]
I suspect that `sound_play` process with japanese voice (`voice_text`) make cpu load super high on PR2 real robot when deployed long time.

Once PR2 cpu load is over 50, which is too high to perform any task, and soon after `rosnode kill sound_node_jp`, cpu load is back to just 6.

I'm not yet sure what part are actually problem, but I just wanted to notify this.

**Comment by k-okada** [comment]
do you mean the  cpu load is not so high just after starting pr2.launch and
becomes 50 after few hours?

--
◉ Kei Okada

**Comment by furushchev** [comment]
after a lot of `say` ing, I think. I suspect that `sound_play` process has a lot of file descriptors left to be open.

**Comment by k-okada** [comment]
https://github.com/ros-drivers/audio_common/blob/hydro-devel/sound_play/scripts/soundplay_node.py
uses threading so that's may be problem?

--
◉ Kei Okada

**Comment by furushchev** [comment]
I think the main reason of high load is comming from keeping many file descriptors.
Opened issue at upstream.
https://github.com/ros-drivers/audio_common/issues/75

**Comment by furushchev** [comment]
Sent Pull request to upstream.
Now I'm working on porting to hydro with minimum change.
(But some bugs cannot be fixed in minimum change)

**Comment by furushchev** [comment]
done https://github.com/ros-drivers/audio_common/pull/78

**Comment by furushchev** [comment]
created deb binary
[ros-hydro-sound-play_0.2.99-0precise_amd64.zip](https://github.com/jsk-ros-pkg/jsk_common/files/343037/ros-hydro-sound-play_0.2.99-0precise_amd64.zip)
