### ISSUE TITLE
terminal is hidden when executing rossetip

### ISSUE THREAD

**Issue by yuki-asano** [jsk-ros-pkg/jsk_common#1494]
rossetipをすると、(rossetmasterだったかも)
添付のようにターミナルが隠れてしまう状況になったので報告いたします。
その時の、envの結果も添付いたします。

![rossetip-bug](https://cloud.githubusercontent.com/assets/6872136/20886445/5cc25220-bb39-11e6-9547-376fd175c8da.png)

[env.txt](https://github.com/jsk-ros-pkg/jsk_common/files/631161/env.txt)

**Comment by furushchev** [comment]
@yuki-asano どれが隠れてしまった画面でしょうか？

`env.txt`の`PS1=\[\033[00;31m\][http://192.168.1.111:11311][192.168.1.120]\[\033[00m\] `という記述を見ると、表示は画像の左ターミナルのようになるのが正しいように感じます。

またターミナルが隠れるとはどういうことでしょうか？

**Comment by yuki-asano** [comment]
隠れているといっているのは、左の画面のことです。
本来、mech-user@みたいにカレントディレクトリが表示されると思いますが、
それが[...][....]で隠れてしまっているという意味でした。

**Comment by furushchev** [comment]
なるほど。ちなみにhistoryも保存されていたりしませんか？

**Comment by furushchev** [comment]
ソースコードと最近のメールの流れを読んだ上での完全な推測ですが、 `~/.bashrc`に、

```bash
source /opt/ros/kinetic/setup.bash
export ROS_MASTER_URI=http://192.168.1.111:11311
```

と書いて、

```bash
$ rossetip
```

すると再現する気がしました。

**Comment by yuki-asano** [comment]
historyは保存していないですね。

> ソースコードと最近のメールの流れを読んだ上での完全な推測ですが、 ~/.bashrcに、
> 
> source /opt/ros/kinetic/setup.bash
> export ROS_MASTER_URI=http://192.168.1.111:11311
> と書いて、
> 
> $ rossetip
> すると再現する気がしました。

再現しないですね。
これ演習中によく起きていた問題で、
自分のPCだと再現しないんですよね。。

**Comment by wkentaro** [comment]
@h-kamada これと似た感じに前なっていませんでした？

2016年12月5日(月) 23:30 Yuki Asano <notifications@github.com>:

**Comment by furushchev** [comment]
@yuki-asano 

> 再現しないですね。

うーん、僕の手元で、apt (ただしshadow-fixed)から入れると再現するのですが。。これもおかしいですね。

`type rossetmaster`
と
`type rossetip`
と再現しない @yuki-asano のPCでうって、出力を確かめてくれますか？

**Comment by wkentaro** [comment]
> Cc: @wkentaro (53c58ac) 直せそうかな?

ん、僕のせいですか？

**Comment by wkentaro** [comment]
indigoでshadow-fixed aptだとこうなります。
```
% bash 
wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ source /opt/ros/indigo/setup.bash
wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ rossetip
set ROS_IP and ROS_HOSTNAME to 133.11.216.106
wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ rossetmaster 192.168.1.11
set ROS_MASTER_URI to http://192.168.1.11:11311
[http://192.168.1.11:11311][133.11.216.106] wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ rossetlocal
set ROS_MASTER_URI to http://localhost:11311
wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ source /opt/ros/indigo/setup.bash
wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ export ROS_MASTER_URI=http://192.168.1.111:11311
wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$ rossetip
set ROS_IP and ROS_HOSTNAME to eth1
[http://192.168.1.111:11311][eth1] wkentaro@hoop:~/Projects/objdepth/src/pascal3d-toolkit/src$
```

**Comment by furushchev** [comment]
https://github.com/jsk-ros-pkg/jsk_common/commit/53c58ac9b66401df385851f78bd40c9c60989fce#diff-48005ba849f01087afb5a38e0561c822R45

で`ROS_MASTER_URI`をrossetmasterでセットすることを想定している気がするけど、自分で`export`して設定しちゃってから`_update_XX`が呼ばれると、

https://github.com/jsk-ros-pkg/jsk_common/commit/53c58ac9b66401df385851f78bd40c9c60989fce#diff-48005ba849f01087afb5a38e0561c822R30

で空文字列が`PS1`に設定されちゃう気がする。

https://github.com/jsk-ros-pkg/jsk_common/commit/53c58ac9b66401df385851f78bd40c9c60989fce#diff-48005ba849f01087afb5a38e0561c822R30
のコミットは名前が`Merge`になっているけど、Mergeだけじゃなくて、関数の中身が変わっていて、Authorが @wkentaro になっているので、なにかこだわりがあるかと思ったのです。
間にコミットがいくつかあったならごめん。

**Comment by wkentaro** [comment]
> 53c58ac#diff-48005ba849f01087afb5a38e0561c822R45

でROS_MASTER_URIをrossetmasterでセットすることを想定している気がするけど、自分でexportして設定しちゃってから_update_XXが呼ばれると、

なるほど。となると僕のせいですね.. 直しておきます。

**Comment by furushchev** [comment]
僕の方だと

```
furushchev@ThinkPad-P50:~/ros/indigo/build/darknet/darknet_ext-prefix/src/darknet_ext-stamp$ rossetip
set ROS_IP and ROS_HOSTNAME to 134.102.118.226
furushchev@ThinkPad-P50:~/ros/indigo/build/darknet/darknet_ext-prefix/src/darknet_ext-stamp$ export ROS_MASTER_URI=http://192.168.1.111:11311
furushchev@ThinkPad-P50:~/ros/indigo/build/darknet/darknet_ext-prefix/src/darknet_ext-stamp$ rossetip
set ROS_IP and ROS_HOSTNAME to eth0
[http://192.168.1.111:11311][eth0] 
```

になります。実は最初に`rossetip`をするのもポイントだったかもしれない。

**Comment by yuki-asano** [comment]
ちょい遅れましたが、結果は添付のようになりました。
![sukusyo](https://cloud.githubusercontent.com/assets/6872136/20889009/b06dee38-bb44-11e6-8c6a-4354fb807a4b.png)

> になります。実は最初にrossetipをするのもポイントだったかもしれない。

確かに、演習中
rossetmaster
rossetip
の順番だとダメだけど、
rossetip
rossetmaster
だとうまくいくという状況がありました。

他にも、
rossetipを二回実行するとバグるのもこれだったりする？

**Comment by furushchev** [comment]
> rossetipを二回実行するとバグるのもこれだったりする？

それは僕の入れた別のバグだと思います（大変失礼しました。）がどうでしょうか？ #1472 
を見てみて、その症状と同じなら、 https://github.com/jsk-ros-pkg/jsk_common/pull/1487 で修正済みですが、まだaptの方には行き渡っていないという状況です。

**Comment by wkentaro** [comment]
このissueは https://github.com/jsk-ros-pkg/jsk_common/pull/1495 で直ると思います。

**Comment by yuki-asano** [comment]
@furushchev @wkentaro 
早速ありがとう！
対応早いですね．

**Comment by robograffitti** [comment]
.bashrc に rossetmaster; rossetip で書いていたら、このような症状が出ました。

試しに.bashrcからコメントアウトして、起動後にrossetmaster; rossetip にするとこのようにならなかったようなので、ログインシェルでrossetmaster; rossetipの順番で実行されると、この症状が出ました。

一旦、rossetip; rossetmasterの順番で実行するようにして回避してるので特に問題になってませんが、一応、報告しておきます。

![Screenshot from 2022-11-04 14-28-32](https://user-images.githubusercontent.com/5218765/199899958-8bbf9733-cf2c-4176-a702-1fd166ede841.png)
