### ISSUE TITLE
Request of Release: 2.2.3

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#1510]

**Comment by k-okada** [comment]
ok, released -> https://github.com/jsk-ros-pkg/jsk_common/commit/af48f7b09a3609df90b3823c2299dd7b9fed6e24
please consider adding filenmae into commit log, so we can create CHANGELOG easily (or change catkin_generate_changelog)

**Comment by wkentaro** [comment]
I see. Thank you.
