### ISSUE TITLE
[jsk_network_tools] ros service

### ISSUE THREAD

**Issue by chibi314** [jsk-ros-pkg/jsk_common#1521]
@furushchev 

バクイです。
jsk_network_toolsはros serviceをサポートしてますか？

**Comment by furushchev** [comment]
`jsk_network_tools` == `silverhammer`という仮定でお答えすると、serviceに対応していないと思います。
（UDPでRPCをするのは結構勇気が要りそうです。）

**Comment by chibi314** [comment]
了解です。ありがとうございました。

**Comment by k-okada** [comment]
そもそもやりたいこと(1) => （思いついた解決策：silverhammerでserviceを使う）(2)=> できない(3)

(3)の返事が来たからと言って、直ちに(1)が出来ない、ということではなくて、
(1)->(2) の変換を間違えている可能性もあるので、質問するときは、何をしたいか、から説明するのが良いと思います．
例えば、ROSのトピック通信通信そのものはUDPで送ることが出来ます．
http://docs.ros.org/api/roscpp/html/classros_1_1TransportHints.html#
a5791caf5a3f38b439ccf60abdb5bf7b2



--
◉ Kei Okada


2017-05-02 16:52 GMT+09:00 Tomoki Anzai <notifications@github.com>:
