### ISSUE TITLE
Release 2.2.6

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_common#1567]
Maybe waiting for solving https://github.com/jsk-ros-pkg/jsk_common/issues/1562

**Comment by furushchev** [comment]
@wkentaro How is going about pending pull requests for 2.2.6?

**Comment by furushchev** [comment]
@k-okada Now all depending pull requests are ready to be merged. Please merge and release a new version.

**Comment by furushchev** [comment]
@k-okada This blocks https://github.com/jsk-ros-pkg/jsk_robot/pull/827 for a long time.

**Comment by k-okada** [comment]
Done https://github.com/ros/rosdistro/pull/16691, https://github.com/ros/rosdistro/pull/16692

**Comment by furushchev** [comment]
@k-okada Thank you very much!!
