### ISSUE TITLE
update install instructions

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_common#1580]
```
Sorry that might be old instruction
1) install from binary
apt-get install ros-kinetic-jsk-common
2) install from source
mkdir -p catkin_ws/src
cd catkin_ws/src
git clone http://github.com/jsk-ros-pkg/jsk_common
cd ..
rosdep install -y -r --from-path . --ignore-src
catkin build
```

cc: @ericlesaquiles, @k-okada, @Affonso-Gui

**Comment by ericlesaquiles** [comment]
Sent PR with updated install instructions on README @furushchev  @k-okada  @Affonso-Gui

**Comment by iory** [comment]
This issue seems like solved by this PR. https://github.com/jsk-ros-pkg/jsk_common/pull/1581/files
@furushchev 
Can you close this issue?

**Comment by iory** [comment]
Thanks!
