### ISSUE TITLE
tf_reconfigure_publisher.py is missing in CMakeLists.txt

### ISSUE THREAD

**Issue by awesome-manuel** [jsk-ros-pkg/jsk_common#1653]
`tf_reconfigure_publisher.py` is not installed a binary be cmake.

**Comment by k-okada** [comment]
thanks should be fixed in
https://github.com/jsk-ros-pkg/jsk_common/pull/1655
--
◉ Kei Okada



2020年9月21日(月) 20:47 Manuel Stahl <notifications@github.com>:
