### ISSUE TITLE
Error: package 'jsk_rosbag_tools' not found

### ISSUE THREAD

**Issue by Sandeepsabbella** [jsk-ros-pkg/jsk_common#1759]
After installing jsk_common, I am unable to run the command `rosrun jsk_rosbag_tools bag_to_video.py $(rospack find jsk_rosbag_tools)/samples/data/20220530173950_go_to_kitchen_rosbag.bag .... ` as the package `jsk_rosbag_tools` is not being found by rospack. Tried both installation from the sudo command and building from source. Still the issue remains. I am using `ROS_NOETIC`. 

Please let me know if there is any fix for this.

**Comment by iory** [comment]
The jsk_rosbag_tools is not still released. So, please build jsk_rosbag_tools in your workspace.

**Comment by k-okada** [comment]
released https://github.com/ros/rosdistro/pull/43881
Close #1759
