### ISSUE TITLE
cannot access nm30 camera by using opt_camera pkg

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_common#205]
_This post was originally posted at http://sourceforge.net/p/jsk-ros-pkg/tickets/210_

nm30をPC (ubuntu 12.04, 32bit, 64bit) につなげて、
rosmake opt_camera
roslaunch opt_camera optnm33_camera_node.lanuch
すると、
UVCIOC_CTRL_GET: name = Firmware Version, sel = 0x01, size = 32, data =
ioctl error Invalid argument
ERROR : try sudo -E ./bin/init_xu_register
としてプロセスが終了します。

sudo -E ./bin/init_xu_register
してみましたが、以下のようにでてnm30のパラメータなどにアクセス
できないようです。

;; video capabilities /dev/video0(3)
;; vd.driver         = uvcvideo
;; vd.card           = Integrated Camera
;; vd.buf_info       = usb-0000:00:1a.0-1.6
;; vd.version        = 197166
;; video capabilities /dev/video1(4)
;; vd.driver         = uvcvideo
;; vd.card           = NM30 Ultra Wideview Camera
;; vd.buf_info       = usb-0000:00:14.0-2
;; vd.version        = 197166
*******_XU registration**_*********
XU add error:Firmware Version
XU add error:Flash Parameter
XU add error:Flip Screen
XU add error:small Hemisphere
XU add error:Analog Video
XU add error:Median Filter
XU add error:Push Button
XU add error:Pending PTZR
XU add error:Auto Pan
XU add error:JPEG Quality
XU add error:Serial ID
XU add error:Info Display
XU add error:Capture Fps
XU add error:Actual Fps
XU add error:Lens Type
XU add error:XPan Absolute
XU add error:XTilt Absolute
XU add error:XRoll Absolute
XU add error:XZoom Absolute
XU add error:Location Absolute
XU add error:XGain Absolute

ただ、luvcview -d /dev/video1みたいにすると、画像がキャプチャできて、
src/opt_nm33_uvc/opt_nm33_camera.cpp
の
  if ( strcmp(getFirmwareVersion().c_str(), "") == 0 ) {
    fprintf(stderr, "ERROR : try sudo -E ./bin/init_xu_register\n");
    //exit(1);  
  }
のexitをこのようにコメントアウトして、エラーを無視すると、
このプログラムからもキャプチャできてrostopic がでるようになります。

急ぎではないですが、ご報告まで。

**Comment by aginika** [comment]
T430でnm33_nodeを実行すると以下のようになってしまい、
/init_xu_register
をしてもしたのようになり再度rosrunをしても結果は変わりません。
何をしたらよいでしょうか？
```
$ rosrun opt_camera nm33_node
Opening device '/dev/video0'
video capabilities
cap.driver        =  uvcvideo
cap.card          =  Integrated Camera
cap.buf_info      =  usb-0000:00:1a.0-1.6
cap.version       =  198669
cap.capabilities  =  0x84000001  VIDEO_CAPTURE STREAMING
cap.width         =  640
cap.height        =  480
UVC_GET_CUR: name = Firmware Version, sel = 0x01, size = 32, data =
ioctl error No such file or directory
ERROR : try sudo -E ./bin/init_xu_register
```

init_xu_registerの結果は以下です。
```
$ sudo /opt/ros/hydro/lib/opt_camera/init_xu_register
;; video capabilities /dev/video0(3)
;; vd.driver         = uvcvideo
;; vd.card           = Integrated Camera
;; vd.buf_info       = usb-0000:00:1a.0-1.6
;; vd.version        = 198669
;; video capabilities /dev/video1(4)
;; vd.driver         = uvcvideo
;; vd.card           = NM30 Ultra Wideview Camera
;; vd.buf_info       = usb-0000:00:14.0-2
;; vd.version        = 198669
********XU registration************
XU mapping succeeded: Firmware Version
XU mapping succeeded: Flash Parameter
XU mapping succeeded: Flip Screen
XU mapping succeeded: small Hemisphere
XU mapping succeeded: Analog Video
XU mapping succeeded: Median Filter
XU mapping succeeded: Push Button
XU mapping succeeded: Pending PTZR
XU mapping succeeded: Auto Pan
XU mapping succeeded: JPEG Quality
XU mapping succeeded: Serial ID
XU mapping succeeded: Info Display
XU mapping succeeded: Capture Fps
XU mapping succeeded: Actual Fps
XU mapping succeeded: Lens Type
XU mapping succeeded: XPan Absolute
XU mapping succeeded: XTilt Absolute
XU mapping succeeded: XRoll Absolute
XU mapping succeeded: XZoom Absolute
XU mapping succeeded: Location Absolute
XU mapping succeeded: XGain Absolute

```

**Comment by hyaguchijsk** [comment]
video0がIntegrated Cameraとなっていてnm33では無いのが原因です．
おそらくvideo1,video2になっているのではないかな．


2015-04-15 19:17 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by terasawa** [comment]
video1になっていたので
rosparam set /nm33_cam/camera_index 1
をしたら解決しました。ありがとうございます。
