### ISSUE TITLE
[image_view_jsk_patch] send patches to upstream 

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_common#706]

**Comment by k-okada** [comment]
I think they are already sent to upstream

https://github.com/ros-perception/image_pipeline/commit/3c4b04df2f2884694dadf4bc597696f9f526561b

https://github.com/jsk-ros-pkg/jsk_common/tree/1f4743d914ff0cf33253e39d1c18a6a4dbf54613/jsk_ros_patch/image_view_jsk_patch

**Comment by garaemon** [comment]
Great, I will remove the package
