### ISSUE TITLE
rossetdefaultが行われると表示が崩れる

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_common#899]
以下のように表示が崩れてしまいます。
```
$ rossetdefault 
set ROS_MASTER_URI to http://local
11311:11311
[http://local
11311:11311][] $
```

**Comment by wkentaro** [comment]
テスト不足でした。
bashの時には`echo -e`をする必要があるので、以下で直しました。
https://github.com/jsk-ros-pkg/jsk_common/pull/900/files#diff-48005ba849f01087afb5a38e0561c822R13

**Comment by aginika** [comment]
ありがとうございます
