### ISSUE TITLE
Capture axis video using mjpeg_capture.sh in jsk_tools?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_common#989]
To record baxter's motions I created a script to capture axis video's mjpeg stream.
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/scripts/record_axis_video.py

I'd like to add this kind of script to `jsk_tools`, and found `mjpeg_capture.sh`.
Is that possible to capture axis video using the script?
or should I add a new one?

**Comment by garaemon** [comment]
like this:
```
ffmpeg -f mjpeg -i http://user:passwd@133.11.216.150/axis-cgi/mjpg/video.cgi\?resolution\=800x600 hoge.mpeg
```

**Comment by wkentaro** [comment]
So can I replace mjpeg_capture.sh with ffmpeg?
I don't understand the usage of mjepg_capture.sh which is now in the jsk_tools pkg.

**Comment by garaemon** [comment]
Please use existing script

**Comment by wkentaro** [comment]
I don't understand what these lines do.
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tools/src/mjpeg_capture.sh#L32-L40

**Comment by wkentaro** [comment]
```
$ ./mjpeg_capture.sh http://user:passwd@133.11.216.141/mjpg/video.mjpg output.mp4
touch: missing file operand
Try 'touch --help' for more information.
```
And timeout in while loop..

**Comment by wkentaro** [comment]
I'd like to add a script like https://github.com/jsk-ros-pkg/jsk_common/pull/998 .

**Comment by garaemon** [comment]
It just waits for other processes which listening to the port to finish for 30 seconds.
I don't know why its required though

**Comment by wkentaro** [comment]
Closing with https://github.com/jsk-ros-pkg/jsk_common/pull/1000
